dist: trusty
sudo: required

language: cpp

before_install:
  # The Coverity Scan certificate-chain is missing an intermediate certificate
  - >
    sudo curl -s -L https://entrust.com/root-certificates/entrust_l1k.cer -o
    /usr/local/share/ca-certificates/entrust_l1k.crt
  - sudo update-ca-certificates
  - >
    echo -n | openssl s_client -connect scan.coverity.com:443 |
    sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' |
    sudo tee -a /etc/ssl/certs/ca-certificates.crt
  - sudo iptables -F
  - mkdir m4
  - autoreconf -fi
  # No multicast support because OpenSSL 1.1 isn't available
  #- ./configure --disable-root-actions --with-noaaport --with-multicast
  - ./configure --disable-root-actions --with-noaaport

addons:
  apt:
    packages:
      - libxml2-dev 
      - libpng12-dev
      - zlib1g-dev
      - libcunit1-dev
      - doxygen
  coverity_scan:
    project:
      name: "Unidata/LDM"
      description: "Event-driven data-distribution package"
    notification_email: emmerson@ucar.edu
    build_command_prepend: true
    build_command:  "make"
#   branch_pattern: master

script: make distcheck

after_failure:
  - pwd
  - cat Makefile
