set nonu aw sm sw=4 nobf ts=8 ai terse ic ws wm=0 redraw
set para=IPLPPPQPTPP\ LIpplpipnpbp'
set shell=bash
ab ldm <a href="glindex.html#LDM">LDM</a>
ab upldm <a href="glindex.html#upstream_LDM">upstream LDM</a>
ab downldm <a href="glindex.html#downstream_LDM">downstream LDM</a>
ab ling LDM <a href="glindex.html#ingester">ingester</a>
ab ldec LDM <a href="glindex.html#decoder">decoder</a>
ab md <a href="glindex.html#metadata">metadata</a>
ab ft <a href="glindex.html#feedtype">feedtype</a>
ab pid <a href="glindex.html#identifier">data-product identifier</a>
ab psig <a href="glindex.html#signature">data-product signature</a>
ab ptime <a href="glindex.html#creation-time">data-product creation-time</a>
ab psize <a href="glindex.html#product_size">data-product size</a>
ab dp <a href="glindex.html#data-product">data-product</a>
ab dpd <a href="glindex.html#data-product_data">data-product data</a>
ab idd <a href="glindex.html#IDD">IDD</a>
ab rpcldmd <a href="glindex.html#ldmd"><tt>ldmd</tt></a>
ab pq <a href="glindex.html#product-queue">product-queue</a>
ab pqa <a href="glindex.html#pqact"><tt>pqact</tt></a>
ab logf <a href="glindex.html#logfile">LDM logfile</a>
ab feedme <a href="glindex.html#FEEDME">FEEDME</a>
ab notifyme <a href="glindex.html#NOTIFYME">NOTIFYME</a>
ab hereis <a href="glindex.html#HEREIS">HEREIS</a>
ab comingsoon <a href="glindex.html#COMINGSOON">COMINGSOON</a>
ab blkdata <a href="glindex.html#BLKDATA">BLKDATA</a>
ab hiya <a href="glindex.html#HIYA">HIYA</a>
ab luser <a href="glindex.html#LDM_user">LDM user</a>
ab ere <a href="glindex.html#ERE">ERE</a>
ab ldmdc <a href="glindex.html#ldmd.conf"><tt>ldmd.conf</tt></a>
ab pqactc <a href="glindex.html#pqact.conf"><tt>pqact</tt> configuration-file</a>
ab scourc <a href="glindex.html#scour.conf"><tt>scour.conf</tt></a>
ab faq <a href="glindex.html#FAQ">FAQ</a>
ab ladmin <a href="glindex.html#ldmadmin"><tt>ldmadmin</tt></a>
ab ee <a href="glindex.html#EXEC_entry"><tt>EXEC entry</tt></tt></a>
ab regutil <a href="glindex.html#regutil"><tt>regutil</tt></a>
ab ldmreg <a href="glindex.html#LDM_registry">LDM registry</a>
ab pqsurf <a href="glindex.html#pqsurf">pqsurf</a>
