/* DO NOT EDIT THIS FILE. It was created by extractDecls */
/*
 *   Copyright 2011, University Corporation for Atmospheric Research.
 *   See file COPYRIGHT for copying and redistribution conditions.
 */

#ifndef GET_FACILITY_NAME_H
#define GET_FACILITY_NAME_H

/**
 * Returns the name corresponding to a logging facility.
 *
 * @return The name corresponding to the given logging facility.
 */
const char* getFacilityName(
    const unsigned    facility) /**< [in] Integer representation of the logging
                                  *  facility */;

#endif
