name: On Push

on:
  push:
    branches: [ "devel", "main" ]
#    branches: [ "*" ]

jobs:
  check:
    permissions:
      actions: read
      contents: read
      security-events: write

    environment: Publish

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
#        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - run: mkdir m4

      - name: Provision Ubuntu
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install doxygen
          autoreconf -fi

      - name: Provision MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install autoconf@2.69
          brew install automake
          brew install doxygen
          /usr/local/opt/autoconf@2.69/bin/autoreconf -fi

      - name: Initialize CodeQL
        if: matrix.os == 'ubuntu-22.04' &&  github.ref_name == 'devel'
        uses: github/codeql-action/init@v2
        with:
          languages: "cpp"

      - name: Make Distribution
        run: |
          ./configure --prefix=/tmp/ldm --with-noaaport --with-gribinsert \
            || { cat configure; exit 1; }
          if test "${{ github.ref_name }}" = "main"; then
            make dist
          else
            make distcheck
          fi

      - name: Perform CodeQL Analysis
        if: matrix.os == 'ubuntu-22.04' &&  github.ref_name == 'devel'
        uses: github/codeql-action/analyze@v2
        with:
          category: "cpp"

#        if: matrix.os == 'ubuntu-22.04'

      - name: Publish Distribution and Documentation
        if: matrix.os == 'ubuntu-22.04' && github.ref_name == 'main'
        env:
          USER: ${{ secrets.NEXUS_USER }}
          PW: ${{ secrets.NEXUS_PW }}
        run: |
          version=`ls *.gz | sed -r 's/ldm-([0-9]+(\.[0-9]+)*)\.tar.gz/\1/'`
          curl -u "$USER":"$PW" \
            -T *.gz https://artifacts.unidata.ucar.edu/repository/downloads-ldm/$version/ \
            -T *.gz https://artifacts.unidata.ucar.edu/repository/downloads-ldm/current/

          make install
          cd /tmp/ldm/share/doc/ldm
          find . -type f | sed 's/^\.\///' | while read path; do
            curl -u "$USER":"$PW" \
              -T $path https://artifacts.unidata.ucar.edu/repository/docs-ldm/$version/$path \
              -T $path https://artifacts.unidata.ucar.edu/repository/docs-ldm/current/$path
          done