.TH REGUTIL 1 "2010-01-13"
.SH NAME
regutil \- Utility for Managing the LDM Registry
.SH SYNOPSIS
.HP
.ft B
regutil
.nh
\fR[\fB-d \fIdir\fR]
\fR\fB-c\fR
\fR[\fB-l \fIlogdest\fR]
.hy
.ft
.HP
.ft B
regutil
.nh
\fR[\fB-d \fIdir\fR]
\fR[\fB-l \fIlogdest\fR]
\fR\fB-R\fR
.hy
.ft
.HP
.ft B
regutil
.nh
\fR[\fB-d \fIdir\fR]
\fR[\fB-l \fIlogdest\fR]
\fR[\fB-q\fR]
\fR[\fIpath ...\fR]
.hy
.ft
.HP
.ft B
regutil
.nh
\fR[\fB-d \fIdir\fR]
\fR[\fB-l \fIlogdest\fR]
\fR[\fB-q\fR]
\fB-r \fP
\fR\fIpath ...\fR
.hy
.ft
.HP
.ft B
regutil
.nh
\fR[\fB-d \fIdir\fR]
\fR[\fB-l \fIlogdest\fR]
\fR(\fB-b \fIbool\fR|\fB-h \fIsig\fR|\fB-s \fIstring\fR|\fB-t \fItime\fR|\fB-u \fIuint\fR)
\fIvalpath\fR
.hy
.ft
.SH DESCRIPTION
.PP
This program manages the LDM registry.
.PP
The first execution form creates the registry if it doesn't already exist.
.PP
The second execution form resets the registry, performing as much recovery
as possible without removing any data.
.PP
The third execution form prints to the standard output stream all
pathname/value pairs in the registry that have one of the \fIpath\fP arguments
as a prefix.  If no pathname arguments are specified,
then all pathname/value pairs are printed.
.PP
The fourth execution form removes from the registry all
pathname/value pairs that have one of the \fIpath\fP arguments
as a prefix.
.PP
The last execution form sets a pathname/value pair in the registry.  One of the
options \fB-b\fP, \fB-h\fP, \fB-s\fP, \fB-t\fP, or \fB-u\fP must be specified.
\fIvalpath\fP is the absolute pathname of the parameter to be set.
.SH OPTIONS
.TP
.BI "-b " bool
The boolean value to which to set the parameter. One of \fBTRUE\fP, or 
\fBFALSE\fP.
.TP
.BI "-c"
Create the registry if it doesn't already exist.
.TP
.BI "-d " dir
Pathname of the directory containing the LDM registry.  The default is
\fB$LDMHOME/etc\fP.
.TP
.BI "-h " signature
The signature value to which to set the parameter.  The signature shall be
specified as a 32 character hexadecimal digit.
.TP
.BI "-l " logdest
Log to \fIlogdest\fP. One of \fB''\fP (system logging daemon), \fB'-'\fP
(standard error stream), or file \fIlogdest\fP. Default is the standard error
stream if the process has a controlling terminal (i.e., the process isn't a
daemon); otherwise, either the LDM log file or the system logging daemon
(execute this program with just the option \fB'-?'\fP to determine which).
.TP
.BI "-q"
Causes the utility to be "quiet" (i.e., to not write an error message to the
standard error stream) if a value or node doesn't exist.
.TP
.BI "-R"
Resets the registry.  Does as much recovery as possible.
.TP
.BI "-s " string
The string value to which to set the parameter.
.TP
.BI "-t " time
The time value to which to set the parameter.  The time shall be specified as
\fBYYYYMMDDThhmmss[.uuuuuu]\fP, where \fB[.uuuuuu]\fP denotes an optional
microsecond portion (without the brackets).
.TP
.BI "-u " uint
The unsigned integer value to which to set the parameter.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
Incorrect usage (\fIi.e.\fP, command-line syntax error).  A "usage" 
error-message should have been printed.
.TP
.B 2
At least one of the referenced entries didn't exist.  All the other entries
were correctly processed.  Error messages identifying the missing entries
should have been printed.
.TP
.B 3
System error.  An error message should have been printed.
.SH SUPPORT
.LP
If you have problems with this program, then you should first examine the 
LDM email archive for similar problems and how they were solved.
The email archive is available via the following URL:
.sp
.RS
\fBhttp://www.unidata.ucar.edu/software/ldm/\fP
.RE
.sp
If this does not suffice, then send an inquiry via email -- together will 
all relevant information -- to
.sp
.RS
\fBsupport-ldm@unidata.ucar.edu\fP
.RE
